version: "3.7"

volumes:
    forum-volume:
    
services:

  forum-backend:
    build: forum_back/
    restart: always  # restart docker after virtual environment is down
    volumes: 
      - forum-volume:/usr/src/app/
    environment: 
      - TZ=Asia/Almaty
    ports: 
      -  '4333:4333'
    
  
  forum-front:
    build: forum_front/
    restart: always
    ports: 
      - "3000:3000"
    environment: 
      - CHOKIDAR_USERPOLLING=true
    


#run docker compose: docker-compose up -d
